spring.application.name=raw-material-service
server.port=8081

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/raw_service_db
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

# KAFKA
spring.kafka.bootstrap-servers=localhost:9092

app.kafka.topic=industria-carro
app.service.name=raw-material-service

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true

spring.kafka.producer.properties.spring.json.type.mapping=base_event:com.projeto.rawmaterialservice.dto.BaseEvent

# Serializador da Chave
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Identificação do cliente para monitoramento no Kafka
spring.kafka.producer.client-id=${spring.application.name}
